# Generated by Django 5.2.1 on 2025-11-14 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(help_text='Name of the institution', max_length=255)),
                ('institution_type', models.CharField(choices=[('university', 'University'), ('faculty', 'Faculty / Department'), ('school', 'School / College'), ('training', 'Training Center'), ('company', 'Company'), ('other', 'Other')], help_text='Type of institution', max_length=20)),
                ('contact_name', models.CharField(help_text='Full name of the contact person', max_length=255)),
                ('contact_email', models.EmailField(help_text='Work email of the contact person', max_length=254)),
                ('contact_phone', models.CharField(blank=True, help_text='Phone number (optional)', max_length=50, null=True)),
                ('request_type', models.CharField(choices=[('demo', 'Request a demo'), ('pricing', 'Request pricing'), ('partnership', 'Partnership / Collaboration'), ('technical', 'Technical integration question'), ('general', 'General institutional inquiry')], help_text='Type of request', max_length=20)),
                ('message', models.TextField(blank=True, help_text='Additional message or description', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('contacted', 'Contacted'), ('demo_scheduled', 'Demo Scheduled'), ('completed', 'Completed'), ('archived', 'Archived')], default='pending', help_text='Status of the request', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this request', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Request',
                'verbose_name_plural': 'Contact Requests',
                'db_table': 'contact_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
