# Generated by Django 5.2.1 on 2025-11-17 19:21

from django.db import migrations
from django.contrib.auth.hashers import make_password
from decimal import Decimal


def create_beyza2_data(apps, schema_editor):
    """
    Create complete data for user beyza2 using Django ORM operations.
    This includes: user, instructor, courses, enrollments, assessments, grades, and PO achievements.
    """
    # Get models
    User = apps.get_model('api', 'User')
    ProgramOutcome = apps.get_model('api', 'ProgramOutcome')
    Course = apps.get_model('api', 'Course')
    CoursePO = apps.get_model('api', 'CoursePO')
    Enrollment = apps.get_model('api', 'Enrollment')
    Assessment = apps.get_model('api', 'Assessment')
    StudentGrade = apps.get_model('api', 'StudentGrade')
    StudentPOAchievement = apps.get_model('api', 'StudentPOAchievement')
    
    # Create or get student user "beyza2"
    student, created = User.objects.get_or_create(
        username='beyza2',
        defaults={
            'email': 'beyza2@example.com',
            'first_name': 'Beyza',
            'last_name': 'Student',
            'role': 'STUDENT',
            'student_id': 'STU2024001',
            'department': 'Computer Science',
            'year_of_study': 3,
            'is_active': True,
            'password': make_password('beyza2pass123')
        }
    )
    if not created:
        # Update existing user to ensure correct fields
        student.email = 'beyza2@example.com'
        student.first_name = 'Beyza'
        student.last_name = 'Student'
        student.role = 'STUDENT'
        student.student_id = 'STU2024001'
        student.department = 'Computer Science'
        student.year_of_study = 3
        student.is_active = True
        student.save()
    
    # Create or get instructor "Ahmet Bulut"
    instructor, created = User.objects.get_or_create(
        username='ahmet.bulut',
        defaults={
            'email': 'ahmet.bulut@example.com',
            'first_name': 'Ahmet',
            'last_name': 'Bulut',
            'role': 'TEACHER',
            'department': 'Computer Science',
            'is_active': True,
            'password': make_password('instructor123')
        }
    )
    if not created:
        instructor.email = 'ahmet.bulut@example.com'
        instructor.first_name = 'Ahmet'
        instructor.last_name = 'Bulut'
        instructor.role = 'TEACHER'
        instructor.department = 'Computer Science'
        instructor.is_active = True
        instructor.save()
    
    # Create Program Outcomes
    po1, _ = ProgramOutcome.objects.get_or_create(
        code='PO1',
        defaults={
            'title': 'Engineering Knowledge',
            'description': 'Apply knowledge of mathematics, science, engineering fundamentals and an engineering specialization to the solution of complex engineering problems.',
            'department': 'Computer Science',
            'target_percentage': Decimal('70.00'),
            'is_active': True
        }
    )
    
    po2, _ = ProgramOutcome.objects.get_or_create(
        code='PO2',
        defaults={
            'title': 'Problem Analysis',
            'description': 'Identify, formulate, research literature and analyze complex engineering problems reaching substantiated conclusions using first principles of mathematics, natural sciences and engineering sciences.',
            'department': 'Computer Science',
            'target_percentage': Decimal('70.00'),
            'is_active': True
        }
    )
    
    po3, _ = ProgramOutcome.objects.get_or_create(
        code='PO3',
        defaults={
            'title': 'Design/Development of Solutions',
            'description': 'Design solutions for complex engineering problems and design systems, components or processes that meet specified needs with appropriate consideration for public health and safety, cultural, societal, and environmental considerations.',
            'department': 'Computer Science',
            'target_percentage': Decimal('70.00'),
            'is_active': True
        }
    )
    
    po4, _ = ProgramOutcome.objects.get_or_create(
        code='PO4',
        defaults={
            'title': 'Investigation',
            'description': 'Conduct investigations of complex problems using research-based knowledge and research methods including design of experiments, analysis and interpretation of data, and synthesis of information to provide valid conclusions.',
            'department': 'Computer Science',
            'target_percentage': Decimal('70.00'),
            'is_active': True
        }
    )
    
    # Create Courses
    course1, _ = Course.objects.get_or_create(
        code='CS301',
        academic_year='2024-2025',
        defaults={
            'name': 'Data Structures and Algorithms',
            'description': 'Advanced data structures and algorithm analysis',
            'department': 'Computer Science',
            'credits': 4,
            'semester': 1,  # FALL
            'academic_year': '2024-2025',
            'teacher': instructor
        }
    )
    if not _:
        course1.teacher = instructor
        course1.save()
    
    course2, _ = Course.objects.get_or_create(
        code='CS302',
        academic_year='2024-2025',
        defaults={
            'name': 'Database Systems',
            'description': 'Introduction to database design and management',
            'department': 'Computer Science',
            'credits': 3,
            'semester': 1,  # FALL
            'academic_year': '2024-2025',
            'teacher': instructor
        }
    )
    if not _:
        course2.teacher = instructor
        course2.save()
    
    course3, _ = Course.objects.get_or_create(
        code='CS303',
        academic_year='2024-2025',
        defaults={
            'name': 'Software Engineering',
            'description': 'Software development lifecycle and methodologies',
            'department': 'Computer Science',
            'credits': 4,
            'semester': 2,  # SPRING
            'academic_year': '2024-2025',
            'teacher': instructor
        }
    )
    if not _:
        course3.teacher = instructor
        course3.save()
    
    # Create Course-PO mappings
    CoursePO.objects.get_or_create(
        course=course1,
        program_outcome=po1,
        defaults={'weight': Decimal('1.50')}
    )
    CoursePO.objects.get_or_create(
        course=course1,
        program_outcome=po2,
        defaults={'weight': Decimal('2.00')}
    )
    CoursePO.objects.get_or_create(
        course=course1,
        program_outcome=po3,
        defaults={'weight': Decimal('1.00')}
    )
    
    CoursePO.objects.get_or_create(
        course=course2,
        program_outcome=po1,
        defaults={'weight': Decimal('1.00')}
    )
    CoursePO.objects.get_or_create(
        course=course2,
        program_outcome=po2,
        defaults={'weight': Decimal('1.50')}
    )
    CoursePO.objects.get_or_create(
        course=course2,
        program_outcome=po4,
        defaults={'weight': Decimal('1.50')}
    )
    
    CoursePO.objects.get_or_create(
        course=course3,
        program_outcome=po1,
        defaults={'weight': Decimal('1.00')}
    )
    CoursePO.objects.get_or_create(
        course=course3,
        program_outcome=po3,
        defaults={'weight': Decimal('2.50')}
    )
    CoursePO.objects.get_or_create(
        course=course3,
        program_outcome=po4,
        defaults={'weight': Decimal('1.00')}
    )
    
    # Create Enrollments
    enrollment1, _ = Enrollment.objects.get_or_create(
        student=student,
        course=course1,
        defaults={
            'is_active': True,
            'final_grade': Decimal('85.50')
        }
    )
    
    enrollment2, _ = Enrollment.objects.get_or_create(
        student=student,
        course=course2,
        defaults={
            'is_active': True,
            'final_grade': Decimal('78.00')
        }
    )
    
    enrollment3, _ = Enrollment.objects.get_or_create(
        student=student,
        course=course3,
        defaults={
            'is_active': True,
            'final_grade': Decimal('92.00')
        }
    )
    
    # Create Assessments for Course 1 (CS301)
    assessment1_1, _ = Assessment.objects.get_or_create(
        course=course1,
        title='Midterm Exam 1',
        defaults={
            'description': 'First midterm examination',
            'assessment_type': 'MIDTERM',
            'weight': Decimal('30.00'),
            'max_score': Decimal('100.00'),
            'is_active': True
        }
    )
    assessment1_1.related_pos.set([po1, po2])
    
    assessment1_2, _ = Assessment.objects.get_or_create(
        course=course1,
        title='Final Exam',
        defaults={
            'description': 'Final examination',
            'assessment_type': 'FINAL',
            'weight': Decimal('40.00'),
            'max_score': Decimal('100.00'),
            'is_active': True
        }
    )
    assessment1_2.related_pos.set([po1, po2, po3])
    
    assessment1_3, _ = Assessment.objects.get_or_create(
        course=course1,
        title='Project Assignment',
        defaults={
            'description': 'Semester project',
            'assessment_type': 'PROJECT',
            'weight': Decimal('20.00'),
            'max_score': Decimal('100.00'),
            'is_active': True
        }
    )
    assessment1_3.related_pos.set([po3])
    
    assessment1_4, _ = Assessment.objects.get_or_create(
        course=course1,
        title='Quiz 1',
        defaults={
            'description': 'First quiz',
            'assessment_type': 'QUIZ',
            'weight': Decimal('5.00'),
            'max_score': Decimal('20.00'),
            'is_active': True
        }
    )
    assessment1_4.related_pos.set([po1])
    
    assessment1_5, _ = Assessment.objects.get_or_create(
        course=course1,
        title='Quiz 2',
        defaults={
            'description': 'Second quiz',
            'assessment_type': 'QUIZ',
            'weight': Decimal('5.00'),
            'max_score': Decimal('20.00'),
            'is_active': True
        }
    )
    assessment1_5.related_pos.set([po2])
    
    # Create Assessments for Course 2 (CS302)
    assessment2_1, _ = Assessment.objects.get_or_create(
        course=course2,
        title='Midterm Exam',
        defaults={
            'description': 'Midterm examination',
            'assessment_type': 'MIDTERM',
            'weight': Decimal('35.00'),
            'max_score': Decimal('100.00'),
            'is_active': True
        }
    )
    assessment2_1.related_pos.set([po1, po2])
    
    assessment2_2, _ = Assessment.objects.get_or_create(
        course=course2,
        title='Final Exam',
        defaults={
            'description': 'Final examination',
            'assessment_type': 'FINAL',
            'weight': Decimal('40.00'),
            'max_score': Decimal('100.00'),
            'is_active': True
        }
    )
    assessment2_2.related_pos.set([po2, po4])
    
    assessment2_3, _ = Assessment.objects.get_or_create(
        course=course2,
        title='Database Project',
        defaults={
            'description': 'Database design project',
            'assessment_type': 'PROJECT',
            'weight': Decimal('25.00'),
            'max_score': Decimal('100.00'),
            'is_active': True
        }
    )
    assessment2_3.related_pos.set([po3, po4])
    
    # Create Assessments for Course 3 (CS303)
    assessment3_1, _ = Assessment.objects.get_or_create(
        course=course3,
        title='Midterm Exam',
        defaults={
            'description': 'Midterm examination',
            'assessment_type': 'MIDTERM',
            'weight': Decimal('30.00'),
            'max_score': Decimal('100.00'),
            'is_active': True
        }
    )
    assessment3_1.related_pos.set([po1])
    
    assessment3_2, _ = Assessment.objects.get_or_create(
        course=course3,
        title='Final Exam',
        defaults={
            'description': 'Final examination',
            'assessment_type': 'FINAL',
            'weight': Decimal('35.00'),
            'max_score': Decimal('100.00'),
            'is_active': True
        }
    )
    assessment3_2.related_pos.set([po1, po3])
    
    assessment3_3, _ = Assessment.objects.get_or_create(
        course=course3,
        title='Software Project',
        defaults={
            'description': 'Full-stack software development project',
            'assessment_type': 'PROJECT',
            'weight': Decimal('35.00'),
            'max_score': Decimal('100.00'),
            'is_active': True
        }
    )
    assessment3_3.related_pos.set([po3, po4])
    
    # Create Student Grades for Course 1
    StudentGrade.objects.get_or_create(
        student=student,
        assessment=assessment1_1,
        defaults={
            'score': Decimal('88.00'),
            'feedback': 'Excellent understanding of fundamental concepts.'
        }
    )
    
    StudentGrade.objects.get_or_create(
        student=student,
        assessment=assessment1_2,
        defaults={
            'score': Decimal('85.00'),
            'feedback': 'Good performance overall, minor improvements needed in algorithm complexity analysis.'
        }
    )
    
    StudentGrade.objects.get_or_create(
        student=student,
        assessment=assessment1_3,
        defaults={
            'score': Decimal('90.00'),
            'feedback': 'Outstanding project implementation.'
        }
    )
    
    StudentGrade.objects.get_or_create(
        student=student,
        assessment=assessment1_4,
        defaults={
            'score': Decimal('18.00'),
            'feedback': 'Well done.'
        }
    )
    
    StudentGrade.objects.get_or_create(
        student=student,
        assessment=assessment1_5,
        defaults={
            'score': Decimal('17.00'),
            'feedback': 'Good work.'
        }
    )
    
    # Create Student Grades for Course 2
    StudentGrade.objects.get_or_create(
        student=student,
        assessment=assessment2_1,
        defaults={
            'score': Decimal('75.00'),
            'feedback': 'Solid understanding of database concepts.'
        }
    )
    
    StudentGrade.objects.get_or_create(
        student=student,
        assessment=assessment2_2,
        defaults={
            'score': Decimal('80.00'),
            'feedback': 'Good performance in final exam.'
        }
    )
    
    StudentGrade.objects.get_or_create(
        student=student,
        assessment=assessment2_3,
        defaults={
            'score': Decimal('79.00'),
            'feedback': 'Well-designed database schema.'
        }
    )
    
    # Create Student Grades for Course 3
    StudentGrade.objects.get_or_create(
        student=student,
        assessment=assessment3_1,
        defaults={
            'score': Decimal('90.00'),
            'feedback': 'Excellent understanding of software engineering principles.'
        }
    )
    
    StudentGrade.objects.get_or_create(
        student=student,
        assessment=assessment3_2,
        defaults={
            'score': Decimal('95.00'),
            'feedback': 'Outstanding performance.'
        }
    )
    
    StudentGrade.objects.get_or_create(
        student=student,
        assessment=assessment3_3,
        defaults={
            'score': Decimal('91.00'),
            'feedback': 'Excellent project with clean code and good documentation.'
        }
    )
    
    # Create Student PO Achievements
    # PO1 Achievement
    StudentPOAchievement.objects.get_or_create(
        student=student,
        program_outcome=po1,
        defaults={
            'current_percentage': Decimal('82.50'),
            'total_assessments': 6,
            'completed_assessments': 6
        }
    )
    
    # PO2 Achievement
    StudentPOAchievement.objects.get_or_create(
        student=student,
        program_outcome=po2,
        defaults={
            'current_percentage': Decimal('79.00'),
            'total_assessments': 5,
            'completed_assessments': 5
        }
    )
    
    # PO3 Achievement
    StudentPOAchievement.objects.get_or_create(
        student=student,
        program_outcome=po3,
        defaults={
            'current_percentage': Decimal('88.00'),
            'total_assessments': 4,
            'completed_assessments': 4
        }
    )
    
    # PO4 Achievement
    StudentPOAchievement.objects.get_or_create(
        student=student,
        program_outcome=po4,
        defaults={
            'current_percentage': Decimal('81.00'),
            'total_assessments': 3,
            'completed_assessments': 3
        }
    )


def reverse_beyza2_data(apps, schema_editor):
    """
    Reverse migration - remove data created for beyza2.
    """
    User = apps.get_model('api', 'User')
    ProgramOutcome = apps.get_model('api', 'ProgramOutcome')
    Course = apps.get_model('api', 'Course')
    Enrollment = apps.get_model('api', 'Enrollment')
    Assessment = apps.get_model('api', 'Assessment')
    StudentGrade = apps.get_model('api', 'StudentGrade')
    StudentPOAchievement = apps.get_model('api', 'StudentPOAchievement')
    
    # Delete student data
    try:
        student = User.objects.get(username='beyza2')
        StudentPOAchievement.objects.filter(student=student).delete()
        StudentGrade.objects.filter(student=student).delete()
        Enrollment.objects.filter(student=student).delete()
        # Note: We don't delete courses, assessments, or instructor as they might be used by others
    except User.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_contactrequest'),
    ]

    operations = [
        migrations.RunPython(create_beyza2_data, reverse_beyza2_data),
    ]
