# Generated by Django 5.2.1 on 2025-11-17 19:24

from django.db import migrations
from django.contrib.auth.hashers import make_password
from decimal import Decimal


def populate_all_students_data(apps, schema_editor):
    """
    Populate comprehensive data for ALL students in the system.
    This includes: courses, enrollments, assessments, grades, and PO achievements.
    Normally teachers would fill this, but since teachers aren't ready yet,
    we're populating it from the backend.
    """
    # Get models
    User = apps.get_model('api', 'User')
    ProgramOutcome = apps.get_model('api', 'ProgramOutcome')
    Course = apps.get_model('api', 'Course')
    CoursePO = apps.get_model('api', 'CoursePO')
    Enrollment = apps.get_model('api', 'Enrollment')
    Assessment = apps.get_model('api', 'Assessment')
    StudentGrade = apps.get_model('api', 'StudentGrade')
    StudentPOAchievement = apps.get_model('api', 'StudentPOAchievement')
    
    # Get all students
    all_students = User.objects.filter(role='STUDENT', is_active=True)
    student_count = all_students.count()
    
    if student_count == 0:
        print("No students found. Skipping data population.")
        return
    
    print(f"Populating data for {student_count} students...")
    
    # Get or create instructor
    instructor, _ = User.objects.get_or_create(
        username='ahmet.bulut',
        defaults={
            'email': 'ahmet.bulut@example.com',
            'first_name': 'Ahmet',
            'last_name': 'Bulut',
            'role': 'TEACHER',
            'department': 'Computer Science',
            'is_active': True,
            'password': make_password('instructor123')
        }
    )
    if not _:
        instructor.role = 'TEACHER'
        instructor.department = 'Computer Science'
        instructor.is_active = True
        instructor.save()
    
    # Get or create Program Outcomes
    po1, _ = ProgramOutcome.objects.get_or_create(
        code='PO1',
        defaults={
            'title': 'Engineering Knowledge',
            'description': 'Apply knowledge of mathematics, science, engineering fundamentals and an engineering specialization to the solution of complex engineering problems.',
            'department': 'Computer Science',
            'target_percentage': Decimal('70.00'),
            'is_active': True
        }
    )
    
    po2, _ = ProgramOutcome.objects.get_or_create(
        code='PO2',
        defaults={
            'title': 'Problem Analysis',
            'description': 'Identify, formulate, research literature and analyze complex engineering problems reaching substantiated conclusions using first principles of mathematics, natural sciences and engineering sciences.',
            'department': 'Computer Science',
            'target_percentage': Decimal('70.00'),
            'is_active': True
        }
    )
    
    po3, _ = ProgramOutcome.objects.get_or_create(
        code='PO3',
        defaults={
            'title': 'Design/Development of Solutions',
            'description': 'Design solutions for complex engineering problems and design systems, components or processes that meet specified needs with appropriate consideration for public health and safety, cultural, societal, and environmental considerations.',
            'department': 'Computer Science',
            'target_percentage': Decimal('70.00'),
            'is_active': True
        }
    )
    
    po4, _ = ProgramOutcome.objects.get_or_create(
        code='PO4',
        defaults={
            'title': 'Investigation',
            'description': 'Conduct investigations of complex problems using research-based knowledge and research methods including design of experiments, analysis and interpretation of data, and synthesis of information to provide valid conclusions.',
            'department': 'Computer Science',
            'target_percentage': Decimal('70.00'),
            'is_active': True
        }
    )
    
    # Create courses for current academic year
    academic_year = '2024-2025'
    
    course1, _ = Course.objects.get_or_create(
        code='CS301',
        academic_year=academic_year,
        defaults={
            'name': 'Data Structures and Algorithms',
            'description': 'Advanced data structures and algorithm analysis',
            'department': 'Computer Science',
            'credits': 4,
            'semester': 1,  # FALL
            'academic_year': academic_year,
            'teacher': instructor
        }
    )
    if not _:
        course1.teacher = instructor
        course1.save()
    
    course2, _ = Course.objects.get_or_create(
        code='CS302',
        academic_year=academic_year,
        defaults={
            'name': 'Database Systems',
            'description': 'Introduction to database design and management',
            'department': 'Computer Science',
            'credits': 3,
            'semester': 1,  # FALL
            'academic_year': academic_year,
            'teacher': instructor
        }
    )
    if not _:
        course2.teacher = instructor
        course2.save()
    
    course3, _ = Course.objects.get_or_create(
        code='CS303',
        academic_year=academic_year,
        defaults={
            'name': 'Software Engineering',
            'description': 'Software development lifecycle and methodologies',
            'department': 'Computer Science',
            'credits': 4,
            'semester': 2,  # SPRING
            'academic_year': academic_year,
            'teacher': instructor
        }
    )
    if not _:
        course3.teacher = instructor
        course3.save()
    
    courses = [course1, course2, course3]
    
    # Create Course-PO mappings
    CoursePO.objects.get_or_create(
        course=course1,
        program_outcome=po1,
        defaults={'weight': Decimal('1.50')}
    )
    CoursePO.objects.get_or_create(
        course=course1,
        program_outcome=po2,
        defaults={'weight': Decimal('2.00')}
    )
    CoursePO.objects.get_or_create(
        course=course1,
        program_outcome=po3,
        defaults={'weight': Decimal('1.00')}
    )
    
    CoursePO.objects.get_or_create(
        course=course2,
        program_outcome=po1,
        defaults={'weight': Decimal('1.00')}
    )
    CoursePO.objects.get_or_create(
        course=course2,
        program_outcome=po2,
        defaults={'weight': Decimal('1.50')}
    )
    CoursePO.objects.get_or_create(
        course=course2,
        program_outcome=po4,
        defaults={'weight': Decimal('1.50')}
    )
    
    CoursePO.objects.get_or_create(
        course=course3,
        program_outcome=po1,
        defaults={'weight': Decimal('1.00')}
    )
    CoursePO.objects.get_or_create(
        course=course3,
        program_outcome=po3,
        defaults={'weight': Decimal('2.50')}
    )
    CoursePO.objects.get_or_create(
        course=course3,
        program_outcome=po4,
        defaults={'weight': Decimal('1.00')}
    )
    
    # Create assessments for each course
    # Course 1 assessments
    assessment1_1, _ = Assessment.objects.get_or_create(
        course=course1,
        title='Midterm Exam 1',
        defaults={
            'description': 'First midterm examination',
            'assessment_type': 'MIDTERM',
            'weight': Decimal('30.00'),
            'max_score': Decimal('100.00'),
            'is_active': True
        }
    )
    assessment1_1.related_pos.set([po1, po2])
    
    assessment1_2, _ = Assessment.objects.get_or_create(
        course=course1,
        title='Final Exam',
        defaults={
            'description': 'Final examination',
            'assessment_type': 'FINAL',
            'weight': Decimal('40.00'),
            'max_score': Decimal('100.00'),
            'is_active': True
        }
    )
    assessment1_2.related_pos.set([po1, po2, po3])
    
    assessment1_3, _ = Assessment.objects.get_or_create(
        course=course1,
        title='Project Assignment',
        defaults={
            'description': 'Semester project',
            'assessment_type': 'PROJECT',
            'weight': Decimal('20.00'),
            'max_score': Decimal('100.00'),
            'is_active': True
        }
    )
    assessment1_3.related_pos.set([po3])
    
    assessment1_4, _ = Assessment.objects.get_or_create(
        course=course1,
        title='Quiz 1',
        defaults={
            'description': 'First quiz',
            'assessment_type': 'QUIZ',
            'weight': Decimal('5.00'),
            'max_score': Decimal('20.00'),
            'is_active': True
        }
    )
    assessment1_4.related_pos.set([po1])
    
    assessment1_5, _ = Assessment.objects.get_or_create(
        course=course1,
        title='Quiz 2',
        defaults={
            'description': 'Second quiz',
            'assessment_type': 'QUIZ',
            'weight': Decimal('5.00'),
            'max_score': Decimal('20.00'),
            'is_active': True
        }
    )
    assessment1_5.related_pos.set([po2])
    
    # Course 2 assessments
    assessment2_1, _ = Assessment.objects.get_or_create(
        course=course2,
        title='Midterm Exam',
        defaults={
            'description': 'Midterm examination',
            'assessment_type': 'MIDTERM',
            'weight': Decimal('35.00'),
            'max_score': Decimal('100.00'),
            'is_active': True
        }
    )
    assessment2_1.related_pos.set([po1, po2])
    
    assessment2_2, _ = Assessment.objects.get_or_create(
        course=course2,
        title='Final Exam',
        defaults={
            'description': 'Final examination',
            'assessment_type': 'FINAL',
            'weight': Decimal('40.00'),
            'max_score': Decimal('100.00'),
            'is_active': True
        }
    )
    assessment2_2.related_pos.set([po2, po4])
    
    assessment2_3, _ = Assessment.objects.get_or_create(
        course=course2,
        title='Database Project',
        defaults={
            'description': 'Database design project',
            'assessment_type': 'PROJECT',
            'weight': Decimal('25.00'),
            'max_score': Decimal('100.00'),
            'is_active': True
        }
    )
    assessment2_3.related_pos.set([po3, po4])
    
    # Course 3 assessments
    assessment3_1, _ = Assessment.objects.get_or_create(
        course=course3,
        title='Midterm Exam',
        defaults={
            'description': 'Midterm examination',
            'assessment_type': 'MIDTERM',
            'weight': Decimal('30.00'),
            'max_score': Decimal('100.00'),
            'is_active': True
        }
    )
    assessment3_1.related_pos.set([po1])
    
    assessment3_2, _ = Assessment.objects.get_or_create(
        course=course3,
        title='Final Exam',
        defaults={
            'description': 'Final examination',
            'assessment_type': 'FINAL',
            'weight': Decimal('35.00'),
            'max_score': Decimal('100.00'),
            'is_active': True
        }
    )
    assessment3_2.related_pos.set([po1, po3])
    
    assessment3_3, _ = Assessment.objects.get_or_create(
        course=course3,
        title='Software Project',
        defaults={
            'description': 'Full-stack software development project',
            'assessment_type': 'PROJECT',
            'weight': Decimal('35.00'),
            'max_score': Decimal('100.00'),
            'is_active': True
        }
    )
    assessment3_3.related_pos.set([po3, po4])
    
    # Organize assessments by course
    course_assessments = {
        course1: [assessment1_1, assessment1_2, assessment1_3, assessment1_4, assessment1_5],
        course2: [assessment2_1, assessment2_2, assessment2_3],
        course3: [assessment3_1, assessment3_2, assessment3_3]
    }
    
    # Process each student
    processed = 0
    for student in all_students:
        # Enroll student in all courses
        for course in courses:
            enrollment, created = Enrollment.objects.get_or_create(
                student=student,
                course=course,
                defaults={
                    'is_active': True
                }
            )
            
            # Calculate final grade from assessments
            assessments = course_assessments[course]
            total_weighted_score = Decimal('0.00')
            total_weight = Decimal('0.00')
            
            for assessment in assessments:
                # Generate realistic grade (60-95 range, with some variation)
                # Use student ID hash for consistent but varied grades per student
                student_hash = hash(f"{student.id}_{assessment.id}") % 100
                base_score = Decimal('60') + Decimal(str(student_hash % 35))  # 60-95 range
                
                # Create grade
                grade, _ = StudentGrade.objects.get_or_create(
                    student=student,
                    assessment=assessment,
                    defaults={
                        'score': base_score,
                        'feedback': f'Good performance on {assessment.title}.'
                    }
                )
                
                # Calculate weighted contribution
                percentage = (grade.score / assessment.max_score) * 100
                weighted_contribution = (percentage * assessment.weight) / 100
                total_weighted_score += weighted_contribution
                total_weight += assessment.weight
            
            # Calculate final grade
            if total_weight > 0:
                final_grade = (total_weighted_score / total_weight) * 100
                enrollment.final_grade = final_grade
                enrollment.save()
        
        # Calculate PO achievements for this student
        for po in [po1, po2, po3, po4]:
            # Get all assessments related to this PO
            po_assessments = []
            for course in courses:
                for assessment in course_assessments[course]:
                    if po in assessment.related_pos.all():
                        po_assessments.append(assessment)
            
            if po_assessments:
                # Calculate average achievement for this PO
                total_score = Decimal('0.00')
                total_max = Decimal('0.00')
                completed = 0
                
                for assessment in po_assessments:
                    try:
                        grade = StudentGrade.objects.get(student=student, assessment=assessment)
                        total_score += grade.score
                        total_max += assessment.max_score
                        completed += 1
                    except StudentGrade.DoesNotExist:
                        pass
                
                if total_max > 0:
                    achievement_percentage = (total_score / total_max) * 100
                    
                    StudentPOAchievement.objects.get_or_create(
                        student=student,
                        program_outcome=po,
                        defaults={
                            'current_percentage': achievement_percentage,
                            'total_assessments': len(po_assessments),
                            'completed_assessments': completed
                        }
                    )
        
        processed += 1
        if processed % 10 == 0:
            print(f"  Processed {processed}/{student_count} students...")
    
    print(f"✅ Successfully populated data for {processed} students")


def reverse_populate_all_students_data(apps, schema_editor):
    """
    Reverse migration - remove data created for all students.
    Note: This only removes student-specific data, not courses or assessments.
    """
    User = apps.get_model('api', 'User')
    Enrollment = apps.get_model('api', 'Enrollment')
    StudentGrade = apps.get_model('api', 'StudentGrade')
    StudentPOAchievement = apps.get_model('api', 'StudentPOAchievement')
    
    # Delete all student data
    all_students = User.objects.filter(role='STUDENT')
    StudentPOAchievement.objects.filter(student__in=all_students).delete()
    StudentGrade.objects.filter(student__in=all_students).delete()
    Enrollment.objects.filter(student__in=all_students).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_create_beyza2_data'),
    ]

    operations = [
        migrations.RunPython(populate_all_students_data, reverse_populate_all_students_data),
    ]
