# Generated by Django 5.2.1 on 2025-11-17 19:43

from django.db import migrations
from decimal import Decimal


def update_beyza2_po_achievements(apps, schema_editor):
    """
    Update PO achievements for beyza2 with varied percentages
    (some high, some low) to make it more realistic.
    """
    User = apps.get_model('api', 'User')
    ProgramOutcome = apps.get_model('api', 'ProgramOutcome')
    StudentPOAchievement = apps.get_model('api', 'StudentPOAchievement')
    
    try:
        student = User.objects.get(username='beyza2')
        
        # Update PO achievements with varied percentages
        # PO1: Excellent (95%)
        po1 = ProgramOutcome.objects.get(code='PO1')
        achievement1, _ = StudentPOAchievement.objects.get_or_create(
            student=student,
            program_outcome=po1,
            defaults={
                'current_percentage': Decimal('95.00'),
                'total_assessments': 6,
                'completed_assessments': 6
            }
        )
        achievement1.current_percentage = Decimal('95.00')
        achievement1.save()
        
        # PO2: Good (78%)
        po2 = ProgramOutcome.objects.get(code='PO2')
        achievement2, _ = StudentPOAchievement.objects.get_or_create(
            student=student,
            program_outcome=po2,
            defaults={
                'current_percentage': Decimal('78.00'),
                'total_assessments': 5,
                'completed_assessments': 5
            }
        )
        achievement2.current_percentage = Decimal('78.00')
        achievement2.save()
        
        # PO3: Excellent (92%)
        po3 = ProgramOutcome.objects.get(code='PO3')
        achievement3, _ = StudentPOAchievement.objects.get_or_create(
            student=student,
            program_outcome=po3,
            defaults={
                'current_percentage': Decimal('92.00'),
                'total_assessments': 4,
                'completed_assessments': 4
            }
        )
        achievement3.current_percentage = Decimal('92.00')
        achievement3.save()
        
        # PO4: Needs Attention (65%)
        po4 = ProgramOutcome.objects.get(code='PO4')
        achievement4, _ = StudentPOAchievement.objects.get_or_create(
            student=student,
            program_outcome=po4,
            defaults={
                'current_percentage': Decimal('65.00'),
                'total_assessments': 3,
                'completed_assessments': 3
            }
        )
        achievement4.current_percentage = Decimal('65.00')
        achievement4.save()
        
        # PO5: Good (82%)
        po5 = ProgramOutcome.objects.filter(code='PO5').first()
        if po5:
            achievement5, _ = StudentPOAchievement.objects.get_or_create(
                student=student,
                program_outcome=po5,
                defaults={
                    'current_percentage': Decimal('82.00'),
                    'total_assessments': 4,
                    'completed_assessments': 4
                }
            )
            achievement5.current_percentage = Decimal('82.00')
            achievement5.save()
        
        print(f"✅ Updated PO achievements for {student.username}")
        print(f"  - PO1: 95% (Excellent)")
        print(f"  - PO2: 78% (Good)")
        print(f"  - PO3: 92% (Excellent)")
        print(f"  - PO4: 65% (Needs Attention)")
        if po5:
            print(f"  - PO5: 82% (Good)")
            
    except User.DoesNotExist:
        print("⚠️ User beyza2 not found, skipping PO achievement update")
    except Exception as e:
        print(f"⚠️ Error updating PO achievements: {e}")


def reverse_update_beyza2_po_achievements(apps, schema_editor):
    """Reverse migration - restore original values"""
    # We don't need to reverse this as it's just updating values
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_populate_all_students_data'),
    ]

    operations = [
        migrations.RunPython(update_beyza2_po_achievements, reverse_update_beyza2_po_achievements),
    ]
