# Generated by Django 5.2.1 on 2025-11-24 17:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_update_beyza2_po_achievements'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='LO code (e.g., LO1, LO2, CS301-LO1)', max_length=20)),
                ('title', models.CharField(help_text='LO title (e.g., Understand Data Structures)', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the learning outcome')),
                ('target_percentage', models.DecimalField(decimal_places=2, default=70.0, help_text='Target achievement percentage (default: 70%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(default=True, help_text='Whether this LO is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(help_text='Course this LO belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='learning_outcomes', to='api.course')),
            ],
            options={
                'verbose_name': 'Learning Outcome',
                'verbose_name_plural': 'Learning Outcomes',
                'db_table': 'learning_outcomes',
                'ordering': ['course', 'code'],
                'unique_together': {('course', 'code')},
            },
        ),
    ]
