# Generated by Django 5.2.1 on 2025-11-24 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_learningoutcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='feedback_ranges',
            field=models.JSONField(blank=True, default=list, help_text="List of feedback ranges: [{'min_score': 90, 'max_score': 100, 'feedback': 'Excellent'}, ...]"),
        ),
    ]
