# Generated by Django 5.2.1 on 2025-11-26 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_assessment_feedback_ranges'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Admin/Institution user who created this account (for teachers)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_teachers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='is_temporary_password',
            field=models.BooleanField(default=True, help_text='If True, user must change password before full access'),
        ),
    ]
