# Generated by Django 5.2.1 on 2025-11-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_student_lo_achievement_and_assessment_related_los'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Department name (e.g., Computer Science)', max_length=100, unique=True)),
                ('code', models.CharField(blank=True, help_text='Department code or abbreviation (e.g., CS, EE)', max_length=10, null=True)),
                ('description', models.TextField(blank=True, help_text='Department description', null=True)),
                ('contact_email', models.EmailField(blank=True, help_text='Department contact email', max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, help_text='Department contact phone', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'db_table': 'departments',
                'ordering': ['name'],
            },
        ),
    ]
