# Generated by Django 5.2.1 on 2025-11-29 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('user_created', 'User Created'), ('user_updated', 'User Updated'), ('user_deleted', 'User Deleted'), ('course_created', 'Course Created'), ('course_updated', 'Course Updated'), ('course_deleted', 'Course Deleted'), ('enrollment_created', 'Enrollment Created'), ('enrollment_updated', 'Enrollment Updated'), ('assessment_created', 'Assessment Created'), ('assessment_updated', 'Assessment Updated'), ('grade_assigned', 'Grade Assigned'), ('grade_updated', 'Grade Updated'), ('department_created', 'Department Created'), ('department_updated', 'Department Updated'), ('po_created', 'Program Outcome Created'), ('po_updated', 'Program Outcome Updated'), ('login', 'User Login')], help_text='Type of action performed', max_length=50)),
                ('department', models.CharField(blank=True, help_text='Department name (for filtering)', max_length=100, null=True)),
                ('description', models.TextField(help_text='Description of the action (no sensitive data)')),
                ('related_object_type', models.CharField(blank=True, help_text="Type of related object (e.g., 'User', 'Course')", max_length=50, null=True)),
                ('related_object_id', models.IntegerField(blank=True, help_text='ID of related object', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata (no sensitive data)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(blank=True, help_text='Institution this activity belongs to', limit_choices_to={'role': 'INSTITUTION'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='institution_activity_logs', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, help_text='User who performed this action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'db_table': 'activity_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='activity_lo_created_d8c226_idx'), models.Index(fields=['action_type'], name='activity_lo_action__9e4610_idx'), models.Index(fields=['institution'], name='activity_lo_institu_3894a8_idx'), models.Index(fields=['department'], name='activity_lo_departm_711579_idx')],
            },
        ),
    ]
