# Generated by Django 5.2.1 on 2025-12-02 14:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_activitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action_type',
            field=models.CharField(choices=[('user_created', 'User Created'), ('user_updated', 'User Updated'), ('user_deleted', 'User Deleted'), ('course_created', 'Course Created'), ('course_updated', 'Course Updated'), ('course_deleted', 'Course Deleted'), ('enrollment_created', 'Enrollment Created'), ('enrollment_updated', 'Enrollment Updated'), ('assessment_created', 'Assessment Created'), ('assessment_updated', 'Assessment Updated'), ('grade_assigned', 'Grade Assigned'), ('grade_updated', 'Grade Updated'), ('department_created', 'Department Created'), ('department_updated', 'Department Updated'), ('po_created', 'Program Outcome Created'), ('po_updated', 'Program Outcome Updated'), ('login', 'User Login'), ('password_reset', 'Password Reset')], help_text='Type of action performed', max_length=50),
        ),
        migrations.CreateModel(
            name='AssessmentLO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, help_text='Weight/contribution of this assessment to the LO (default: 1.0)', max_digits=5, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(10.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(help_text='Assessment', on_delete=django.db.models.deletion.CASCADE, related_name='assessment_los', to='api.assessment')),
                ('learning_outcome', models.ForeignKey(help_text='Learning Outcome', on_delete=django.db.models.deletion.CASCADE, related_name='assessment_los', to='api.learningoutcome')),
            ],
            options={
                'verbose_name': 'Assessment-LO Mapping',
                'verbose_name_plural': 'Assessment-LO Mappings',
                'db_table': 'assessment_learning_outcomes',
                'unique_together': {('assessment', 'learning_outcome')},
            },
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='related_los',
        ),
        migrations.AddField(
            model_name='assessment',
            name='related_los',
            field=models.ManyToManyField(blank=True, help_text='Learning outcomes this assessment evaluates (with weights)', related_name='assessments', through='api.AssessmentLO', to='api.learningoutcome'),
        ),
        migrations.CreateModel(
            name='LOPO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, help_text='Weight/contribution of this LO to the PO (default: 1.0, meaning 100%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(10.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learning_outcome', models.ForeignKey(help_text='Learning Outcome', on_delete=django.db.models.deletion.CASCADE, related_name='lo_pos', to='api.learningoutcome')),
                ('program_outcome', models.ForeignKey(help_text='Program Outcome', on_delete=django.db.models.deletion.CASCADE, related_name='lo_pos', to='api.programoutcome')),
            ],
            options={
                'verbose_name': 'LO-PO Mapping',
                'verbose_name_plural': 'LO-PO Mappings',
                'db_table': 'lo_program_outcomes',
                'unique_together': {('learning_outcome', 'program_outcome')},
            },
        ),
        migrations.AddField(
            model_name='learningoutcome',
            name='program_outcomes',
            field=models.ManyToManyField(blank=True, help_text='Program outcomes this LO contributes to', related_name='learning_outcomes', through='api.LOPO', to='api.programoutcome'),
        ),
    ]
