# Generated by Django 5.2.1 on 2025-12-06 15:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_migrate_assessment_pos_to_lo_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='related_pos',
        ),
        migrations.AlterField(
            model_name='assessmentlo',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Weight/contribution of this assessment to the LO (0.01-10.0 scale, where 1.0 = 10%, 10.0 = 100%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(10.0)]),
        ),
        migrations.AlterField(
            model_name='lopo',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Weight/contribution of this LO to the PO (0.01-10.0 scale, where 1.0 = 10%, 10.0 = 100%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(10.0)]),
        ),
    ]
