# Generated by Django 5.2.1 on 2025-12-16 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_related_pos_field'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_hash', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Password History',
                'verbose_name_plural': 'Password History',
                'db_table': 'password_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Password Reset Token',
                'verbose_name_plural': 'Password Reset Tokens',
                'db_table': 'password_reset_tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user', 'created_at'], name='activity_lo_user_id_d23b30_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['related_object_type', 'related_object_id'], name='activity_lo_related_5f156f_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['course', 'is_active'], name='assessments_course__841300_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['due_date'], name='assessments_due_dat_796263_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['assessment_type'], name='assessments_assessm_603d6c_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['created_at'], name='assessments_created_8a51b9_idx'),
        ),
        migrations.AddIndex(
            model_name='contactrequest',
            index=models.Index(fields=['status', 'created_at'], name='contact_req_status_277039_idx'),
        ),
        migrations.AddIndex(
            model_name='contactrequest',
            index=models.Index(fields=['institution_type'], name='contact_req_institu_92f500_idx'),
        ),
        migrations.AddIndex(
            model_name='contactrequest',
            index=models.Index(fields=['request_type'], name='contact_req_request_54b7c2_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['code', 'academic_year'], name='courses_code_674965_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['teacher', 'academic_year'], name='courses_teacher_392da0_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['department', 'academic_year'], name='courses_departm_0f74f4_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['student', 'is_active'], name='enrollments_student_8f846d_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['course', 'is_active'], name='enrollments_course__f06fd5_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['student', 'course'], name='enrollments_student_9c8d9e_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['enrolled_at'], name='enrollments_enrolle_00c691_idx'),
        ),
        migrations.AddIndex(
            model_name='studentgrade',
            index=models.Index(fields=['student', 'assessment'], name='student_gra_student_993d6f_idx'),
        ),
        migrations.AddIndex(
            model_name='studentgrade',
            index=models.Index(fields=['assessment', 'graded_at'], name='student_gra_assessm_a69367_idx'),
        ),
        migrations.AddIndex(
            model_name='studentgrade',
            index=models.Index(fields=['student', 'graded_at'], name='student_gra_student_e49350_idx'),
        ),
        migrations.AddIndex(
            model_name='studentgrade',
            index=models.Index(fields=['score'], name='student_gra_score_727ae7_idx'),
        ),
        migrations.AddIndex(
            model_name='studentloachievement',
            index=models.Index(fields=['student', 'learning_outcome'], name='student_lo__student_2be339_idx'),
        ),
        migrations.AddIndex(
            model_name='studentloachievement',
            index=models.Index(fields=['student', 'current_percentage'], name='student_lo__student_48915b_idx'),
        ),
        migrations.AddIndex(
            model_name='studentloachievement',
            index=models.Index(fields=['learning_outcome', 'current_percentage'], name='student_lo__learnin_ad1ba5_idx'),
        ),
        migrations.AddIndex(
            model_name='studentloachievement',
            index=models.Index(fields=['last_calculated'], name='student_lo__last_ca_a9dd3e_idx'),
        ),
        migrations.AddIndex(
            model_name='studentpoachievement',
            index=models.Index(fields=['student', 'program_outcome'], name='student_po__student_cee0f5_idx'),
        ),
        migrations.AddIndex(
            model_name='studentpoachievement',
            index=models.Index(fields=['student', 'current_percentage'], name='student_po__student_606d7c_idx'),
        ),
        migrations.AddIndex(
            model_name='studentpoachievement',
            index=models.Index(fields=['program_outcome', 'current_percentage'], name='student_po__program_78ec43_idx'),
        ),
        migrations.AddIndex(
            model_name='studentpoachievement',
            index=models.Index(fields=['last_calculated'], name='student_po__last_ca_62ae53_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['student_id'], name='users_student_2d3a08_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'is_active'], name='users_role_a8f2ba_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['department', 'role'], name='users_departm_92986e_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['created_by'], name='users_created_423079_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['created_at'], name='users_created_6541e9_idx'),
        ),
        migrations.AddField(
            model_name='passwordhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='passwordresettoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='passwordhistory',
            index=models.Index(fields=['user', '-created_at'], name='password_hi_user_id_53e9ab_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordresettoken',
            index=models.Index(fields=['token'], name='password_re_token_060a1f_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordresettoken',
            index=models.Index(fields=['user', 'used', 'expires_at'], name='password_re_user_id_1dc59e_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordresettoken',
            index=models.Index(fields=['expires_at'], name='password_re_expires_8e96b7_idx'),
        ),
    ]
