"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
import ssl
from dotenv import load_dotenv


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from backend/.env
load_dotenv(BASE_DIR / '.env')

# Optional: disable SSL verification for SendGrid in dev if explicitly requested
if os.environ.get("SENDGRID_SKIP_SSL_VERIFY", "").lower() == "true":
    ssl._create_default_https_context = ssl._create_unverified_context


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
# Default to True for development, set DJANGO_DEBUG=False in production
DEBUG = os.environ.get('DJANGO_DEBUG', 'True').lower() == 'true'

# SECURITY WARNING: keep the secret key used in production secret!
# In production, SECRET_KEY must be set via environment variable
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    if DEBUG:
        # Only use default in development
        SECRET_KEY = 'django-insecure-g#z9@_6j&#)fl!x#ymg^71a!n_jv_jpt1yh-_337xpf_n1wx0!'
    else:
        raise ValueError("SECRET_KEY environment variable must be set in production!")

allowed_hosts = os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1')
ALLOWED_HOSTS = [host.strip() for host in allowed_hosts.split(',') if host.strip()]

# Production security check
if not DEBUG and (not SECRET_KEY or SECRET_KEY.startswith('django-insecure-')):
    import warnings
    warnings.warn(
        "⚠️  PRODUCTION WARNING: Using insecure SECRET_KEY in production! "
        "Set DJANGO_SECRET_KEY environment variable with a secure key.",
        UserWarning
    )

# Security settings for production
if not DEBUG:
    # Security headers
    SECURE_SSL_REDIRECT = os.environ.get('SECURE_SSL_REDIRECT', 'False').lower() == 'true'
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True


# Application definition

# Check if optional packages are available
try:
    import drf_spectacular
    SPECTACULAR_AVAILABLE = True
except ImportError:
    SPECTACULAR_AVAILABLE = False

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',  # For token blacklisting
    'corsheaders',
    'api',
]

# Add drf_spectacular only if available
if SPECTACULAR_AVAILABLE:
    INSTALLED_APPS.insert(-1, 'drf_spectacular')  # Add before 'api'

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'api.middleware.RequestLoggingMiddleware',  # Request logging
    'api.middleware.RateLimitMiddleware',  # Rate limiting (only in production)
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# PostgreSQL Database Configuration
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_DB', 'acurate_db'),
        'USER': os.environ.get('POSTGRES_USER', 'acurate_user'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'acurate_pass_2024'),
        'HOST': os.environ.get('POSTGRES_HOST', 'localhost'),
        'PORT': os.environ.get('POSTGRES_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'api.User'

# Email / SendGrid configuration
EMAIL_BACKEND = 'sendgrid_backend.SendgridBackend'
SENDGRID_API_KEY = os.environ.get('SENDGRID_API_KEY', '')
SENDGRID_SANDBOX_MODE_IN_DEBUG = False
DEFAULT_FROM_EMAIL = 'beyza.karasahan@live.acibadem.edu.tr'

# --- CORS Ayarları ---
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",   # Next.js dev server
    "http://127.0.0.1:3000",
]

CORS_ALLOW_CREDENTIALS = True

# --- REST Framework Ayarları ---
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    # Exception handling
    'EXCEPTION_HANDLER': 'api.exceptions.custom_exception_handler',
}

# Add API Documentation schema only if drf-spectacular is available
if SPECTACULAR_AVAILABLE:
    REST_FRAMEWORK['DEFAULT_SCHEMA_CLASS'] = 'drf_spectacular.openapi.AutoSchema'

# --- JWT Ayarları ---
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# --- API Documentation (drf-spectacular) ---
# Only define if drf-spectacular is available
if SPECTACULAR_AVAILABLE:
    SPECTACULAR_SETTINGS = {
        'TITLE': 'AcuRate API',
        'DESCRIPTION': 'Academic Performance Analysis System API Documentation',
        'VERSION': '1.0.0',
        'SERVE_INCLUDE_SCHEMA': False,
        'COMPONENT_SPLIT_REQUEST': True,
        'SCHEMA_PATH_PREFIX': '/api/',
        'AUTHENTICATION_WHITELIST': [
            'rest_framework_simplejwt.authentication.JWTAuthentication',
        ],
    }

# --- Caching Configuration ---
# Use local memory cache for development, Redis for production
CACHE_BACKEND = os.environ.get('CACHE_BACKEND', 'local')  # 'local' or 'redis'

if CACHE_BACKEND == 'redis':
    # Redis cache for production
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379/1'),
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            },
            'KEY_PREFIX': 'acurate',
            'TIMEOUT': 300,  # Default timeout: 5 minutes
        }
    }
else:
    # Local memory cache for development
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'acurate-cache',
            'TIMEOUT': 300,  # Default timeout: 5 minutes
            'OPTIONS': {
                'MAX_ENTRIES': 1000,
            }
        }
    }

# Cache key prefixes
CACHE_KEY_PREFIX = 'acurate'
CACHE_TIMEOUT_SHORT = 60  # 1 minute - for frequently changing data
CACHE_TIMEOUT_MEDIUM = 300  # 5 minutes - default
CACHE_TIMEOUT_LONG = 3600  # 1 hour - for relatively static data
CACHE_TIMEOUT_ANALYTICS = 600  # 10 minutes - for analytics/dashboard data

# --- Rate Limiting ---
RATELIMIT_ENABLE = not DEBUG  # Enable in production
RATELIMIT_USE_CACHE = 'default'
RATELIMIT_KEY_PREFIX = 'rl:'

# --- Media Files (for file uploads) ---
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# --- Static Files ---
STATIC_ROOT = BASE_DIR / 'staticfiles'

# --- Logging Configuration ---
# Check if python-json-logger is available
try:
    import pythonjsonlogger.jsonlogger
    JSON_LOGGER_AVAILABLE = True
except ImportError:
    JSON_LOGGER_AVAILABLE = False

# Build formatters dictionary
formatters = {
    'verbose': {
        'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
        'style': '{',
    },
}

# Add JSON formatter only if python-json-logger is available
if JSON_LOGGER_AVAILABLE:
    formatters['json'] = {
        '()': 'pythonjsonlogger.jsonlogger.JsonFormatter',
        'format': '%(asctime)s %(name)s %(levelname)s %(message)s %(pathname)s %(lineno)d',
    }

# Build handlers dictionary
handlers = {
    'console': {
        'class': 'logging.StreamHandler',
        'formatter': 'verbose',
    },
}

# Create logs directory if it doesn't exist
logs_dir = BASE_DIR / 'logs'
os.makedirs(logs_dir, exist_ok=True)

# Add file handler - use json formatter if available, otherwise verbose
file_formatter = 'json' if JSON_LOGGER_AVAILABLE else 'verbose'
handlers['file'] = {
    'class': 'logging.FileHandler',
    'filename': BASE_DIR / 'logs' / 'acurate.log',
    'formatter': file_formatter,
}

# Determine which handlers to use
# Use file handler only if logs directory exists and is writable
log_handlers = ['console', 'file']
loggers_handlers = ['console', 'file']

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': formatters,
    'handlers': handlers,
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': loggers_handlers,
            'level': 'INFO',
            'propagate': False,
        },
        'api': {
            'handlers': loggers_handlers,
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
    },
}
